Article:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            title:
                type: 'String!'
            description:
                type: 'String!'
            publishedAt:
                type: 'DateTime!'
            status:
                type: 'Boolean!'

DateTime:
    type: custom-scalar
    config:
        serialize: ["App\\GraphQL\\Types\\DateTimeType", "serialize"]
        parseValue: ["App\\GraphQL\\Types\\DateTimeType", "parseValue"]
        parseLiteral: ["App\\GraphQL\\Types\\DateTimeType", "parseLiteral"]

