Article:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            title:
                type: 'String!'
            description:
                type: 'String!'
            publishedAt:
                type: 'String!'
            status:
                type: 'Boolean!'
