Query:
    type: object
    config:
        fields:
            Article:
                type: 'Article'
                args:
                    id:
                        description: 'Resolves Article using its id.'
                        type: 'Int!'
                resolve: "@=resolver('Article', [args['id']])"
            Articles:
                type: '[Article]'
                args:
                    ids:
                        type: '[Int]'
                    title:
                        type: 'String'
                    description:
                        type: 'String'
                    status:
                        type: 'Boolean'
                    publishedAt:
                        type: 'String'
                resolve: "@=resolver('Articles', [args])"
