#index:
#    path: /
#    controller: App\Controller\DefaultController::index

overblog_graphql_single_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/single.yaml"
    prefix: /

overblog_graphiql_endpoint:
    resource: "@OverblogGraphiQLBundle/Resources/config/routing.xml"
